[features]
resolution = true
skip-lint = false

[programs.localnet]
firmware = "E7XwWNsXYWn81mVEGNwVfaHBynjZBcGYZ8ZwnfSzYgRB"

[provider]
cluster = "Localnet"
wallet = "keys/deployer.json"

[scripts]
test = "npm test"
